# Generated by Django 5.2.6 on 2025-09-26 14:53

import django.db.models.deletion
import tracking.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgressPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Fecha')),
                ('photo', models.ImageField(upload_to=tracking.models.progress_photo_path, verbose_name='Foto')),
                ('photo_type', models.CharField(choices=[('front', 'Frente'), ('side', 'Lateral'), ('back', 'Espalda')], max_length=20, verbose_name='Tipo de Foto')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notas')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Foto de Progreso',
                'verbose_name_plural': 'Fotos de Progreso',
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='BodyMeasurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Fecha')),
                ('chest', models.FloatField(blank=True, help_text='Medida en centímetros', null=True, verbose_name='Pecho')),
                ('waist', models.FloatField(blank=True, help_text='Medida en centímetros', null=True, verbose_name='Cintura')),
                ('hips', models.FloatField(blank=True, help_text='Medida en centímetros', null=True, verbose_name='Cadera')),
                ('arms', models.FloatField(blank=True, help_text='Medida en centímetros', null=True, verbose_name='Brazos')),
                ('thighs', models.FloatField(blank=True, help_text='Medida en centímetros', null=True, verbose_name='Muslos')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notas')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Medida Corporal',
                'verbose_name_plural': 'Medidas Corporales',
                'ordering': ['-date', '-id'],
                'unique_together': {('user', 'date')},
            },
        ),
        migrations.CreateModel(
            name='WeightRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Fecha')),
                ('weight', models.FloatField(help_text='Peso en kilogramos', verbose_name='Peso')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notas')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Registro de Peso',
                'verbose_name_plural': 'Registros de Peso',
                'ordering': ['-date', '-id'],
                'unique_together': {('user', 'date')},
            },
        ),
    ]
