# Generated by Django 5.2.6 on 2025-09-25 23:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnnualFlow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_closed', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Flujo Anual',
                'verbose_name_plural': 'Flujos Anuales',
                'ordering': ['-year'],
            },
        ),
        migrations.CreateModel(
            name='ExpenseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'verbose_name': 'Categoría de Gasto',
                'verbose_name_plural': 'Categorías de Gastos',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Presupuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_closed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to='finances.expensecategory', verbose_name='Categoría')),
                ('income', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='finances.income')),
            ],
        ),
        migrations.CreateModel(
            name='MonthlyIncomeBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.IntegerField(choices=[(1, 'Enero'), (2, 'Febrero'), (3, 'Marzo'), (4, 'Abril'), (5, 'Mayo'), (6, 'Junio'), (7, 'Julio'), (8, 'Agosto'), (9, 'Septiembre'), (10, 'Octubre'), (11, 'Noviembre'), (12, 'Diciembre')])),
                ('is_closed', models.BooleanField(default=False)),
                ('annual_flow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='income_books', to='finances.annualflow')),
            ],
            options={
                'verbose_name': 'Libro de Ingresos Mensual',
                'verbose_name_plural': 'Libros de Ingresos Mensuales',
                'ordering': ['month'],
                'unique_together': {('annual_flow', 'month')},
            },
        ),
        migrations.AddField(
            model_name='income',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incomes', to='finances.monthlyincomebook'),
        ),
        migrations.CreateModel(
            name='PresupuestoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('url', models.URLField(blank=True)),
                ('descripcion', models.TextField(blank=True)),
                ('costo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_cerrado', models.BooleanField(default=False)),
                ('export_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='presupuesto_items', to='finances.expense')),
                ('presupuesto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='finances.presupuesto')),
            ],
        ),
        migrations.CreateModel(
            name='Remnant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.CharField(default='Remanente mensual', max_length=200)),
                ('transfer_date', models.DateTimeField(auto_now_add=True)),
                ('income_book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remnants', to='finances.monthlyincomebook')),
            ],
            options={
                'verbose_name': 'Remanente',
                'verbose_name_plural': 'Remanentes',
                'ordering': ['-transfer_date'],
            },
        ),
        migrations.CreateModel(
            name='RemnantWithdrawal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.CharField(max_length=200)),
                ('withdrawal_date', models.DateTimeField(auto_now_add=True)),
                ('annual_flow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='withdrawals', to='finances.annualflow')),
            ],
            options={
                'verbose_name': 'Retiro de Remanente',
                'verbose_name_plural': 'Retiros de Remanentes',
            },
        ),
    ]
